CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- users
CREATE TABLE IF NOT EXISTS users(
user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
username VARCHAR(50) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
is_active BOOLEAN DEFAULT FALSE,
is_verified BOOLEAN DEFAULT FALSE,
background_image TEXT,
profole_images TEXT, 
bio VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- posts 
CREATE TABLE IF NOT EXISTS posts (
    post_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    post_img TEXT[], -- multiple images
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- likes
CREATE TABLE IF NOT EXISTS likes(
like_id  UUID PRIMARY KEY DEFAULT uuid_generage_v4(),
user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
post_id UUID REFERENCES posts(post_id) ON DELETE CASCADE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

-- comments
CREATE TABLE IF NOT EXISTS comments(
comment_id UUID PRIMARY KEY DEFAULT uuid_generage_v4(),
user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
post_id UUID REFERENCES posts(post_id) ON DELETE CASCADE,
context TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);



